language: python

#version
python:
  - "2.7"

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# command to install dependencies
install:
  - conda install --yes python=2.7 atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  # Coverage packages are on dan blanchard's binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - python setup.py install
  - pip install --upgrade pip
  - pip --version
  - pip install -r requirements_travis.txt

# command to run tests
script:
  - nosetests --with-cov --cov ubertool --cov-config .coveragerc --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc
