language: python

#version
python:
  - "2.7"

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - nosetests --with-coverage --cover-erase --cover-package=ubertool.ubertool.sip.sip -sv
  - nosetests --with-coverage --cover-erase --cover-package=ubertool.ubertool.stir.stir -sv
  - nosetests --with-coverage --cover-erase --cover-package=ubertool.ubertool.rice.rice -sv
  - nosetests --with-coverage --cover-erase --cover-package=ubertool.ubertool.terrplant.terrplant -sv
  - nosetests --with-coverage --cover-erase --cover-package=ubertool.ubertool.iec.iec -sv
  - nosetests --with-coverage --cover-erase --cover-package=ubertool.ubertool.earthworm.earthworm -sv

after_success:
  - codecov
  - coveralls
