language: python

#version
python:
  - "2.7"

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip --version
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - nosetests --with-coverage -sv

after_success:
  - coveralls
